version: "2"

services:
  web:
    container_name: hubspot-shopper-app-web
    environment:
      NODE_ENV: development
      PORT: 8080
    env_file:
      - .env.development
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./db:/app/db
    ports:
      - 3000:8080
