version: "2"

services:
  web:
    container_name: hubspot-shopper-app-web
    environment:
      NODE_ENV: development
      APP_BASE_URL: http://localhost:8080
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 8080:3000
    command: ["npm", "start"]
